name: example
description: "Example showcasing the use of ImpSheet (predefined workflow)."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  mtrust_imp_kit:
    path: ../../
  mtrust_urp_ble_strategy: ^9.0.0-0
  liquid_flutter: ^15.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
