name: example
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mtrust_imp_kit:
    path: ../
  mtrust_urp_ble_strategy: 
    hosted: 
      url: https://merckgroup.jfrog.io/artifactory/api/pub/dice-mtrust-pub-dev-local
    version: ^8.0.0
  liquid_flutter:
    hosted:
      url: https://merckgroup.jfrog.io/artifactory/api/pub/dice-mtrust-pub-dev-local
    version: ^15.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
