name: mtrust_imp_kit
description: The M-Trust IMP-Kit allows you to integrate the IMP-Reader with
  your mobile applications.
version: 3.0.1
repository: https://github.com/emdgroup/mtrust-imp-kit
environment:
  sdk: ">=3.2.5 <4.0.0"
  flutter: ">=1.17.0"
dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  mtrust_urp_core: ^9.0.1
  mtrust_urp_types: ^6.0.0
  mtrust_urp_ui: ^9.0.1
  liquid_flutter: ^19.0.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  golden_toolkit: ^0.15.0
  mockito: ^5.4.4
  mtrust_urp_virtual_strategy: ^9.0.1
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
