name: example_advanced
description: "Example showcasing the use of ImpReader and building custom workflows."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  mtrust_imp_kit:
    path: ../../
  mtrust_urp_ble_strategy: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
