name: Main - ↩️ pull request

on:
  pull_request:
    branches:
      - main

jobs:
  validate_pr:
    permissions:
      pull-requests: write
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1

  test_version:
    needs: validate_pr
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{secrets.ELEVATED_TOKEN}}

      - name: 📇 Configure git
        run: |
          git fetch --prune --unshallow
          git config --global user.name "GitHub Actions"
          git config --global user.email "gh-actions@emdgroup.com"
        shell: bash

      # Retrieve the new version
      - name: 🔂 Run standard-version
        uses: actions/github-script@v7
        with:
          script: |
            const {execSync} = require('child_process');
            execSync('npx standard-version --dry-run', {stdio: 'inherit'});

  build_example:
    name: Build Example
    needs: test_version
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Prepare Flutter
        uses: emdgroup/mtrust-urp/.github/actions/prepare-flutter@main
        with:
          directory: example/example

      - name: Run static analysis
        run: |
          cd example/example
          flutter analyze --no-fatal-warnings
        shell: bash

      - name: Check licenses
        uses: emdgroup/mtrust-urp/.github/actions/check-dart-licenses@main
        with:
          directory: example/example

  build_advanced_example:
    name: Build Advanced Example
    needs: test_version
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Prepare Flutter
        uses: emdgroup/mtrust-urp/.github/actions/prepare-flutter@main
        with:
          directory: example/example_advanced

      - name: Run static analysis
        run: |
          cd example/example_advanced
          flutter analyze --no-fatal-warnings
        shell: bash

      - name: Check licenses
        uses: emdgroup/mtrust-urp/.github/actions/check-dart-licenses@main
        with:
          directory: example/example_advanced

  build_library:
    name: Build Library
    needs: test_version
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Prepare Flutter
        uses: emdgroup/mtrust-urp/.github/actions/prepare-flutter@main
        with:
          directory: .

      - name: Validate Flutter
        uses: emdgroup/mtrust-urp/.github/actions/validate-flutter@main
        with:
          directory: .
          is_package: true

      - name: Check licenses
        uses: emdgroup/mtrust-urp/.github/actions/check-dart-licenses@main
        with:
          directory: .
